#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_8_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_9_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_10_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_11_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_12_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_13_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_14_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_15_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_16_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_17_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_18_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_20_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_21_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_22_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_24_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_26_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_28_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_32_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_40_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_48_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_60_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_72_Italic;
extern const ILI9341_t3_font_t GeoramaExtraCondensedThin_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
