#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t MontserratAlternatesThin_8_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_9_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_10_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_11_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_12_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_13_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_14_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_15_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_16_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_17_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_18_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_20_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_21_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_22_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_24_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_26_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_28_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_32_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_40_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_48_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_60_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_72_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesThin_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
