#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t MontserratAlternates_8_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_9_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_10_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_11_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_12_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_13_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_14_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_15_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_16_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_17_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_18_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_20_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_21_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_22_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_24_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_26_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_28_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_32_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_40_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_48_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_60_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_72_Bold_Italic;
extern const ILI9341_t3_font_t MontserratAlternates_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
