#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_8_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_9_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_10_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_11_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_12_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_13_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_14_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_15_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_16_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_17_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_18_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_20_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_21_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_22_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_24_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_26_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_28_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_32_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_40_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_48_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_60_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_72_Italic;
extern const ILI9341_t3_font_t MontserratAlternatesSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
