#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_8_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_9_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_10_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_11_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_12_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_13_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_14_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_15_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_16_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_17_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_18_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_20_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_21_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_22_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_24_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_26_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_28_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_32_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_40_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_48_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_60_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_72_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
