#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_8;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_9;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_10;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_11;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_12;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_13;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_14;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_15;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_16;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_17;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_18;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_20;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_21;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_22;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_24;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_26;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_28;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_32;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_40;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_48;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_60;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_72;
extern const ILI9341_t3_font_t FiraSansExtraCondensedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
