#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_8_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_9_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_10_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_11_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_12_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_13_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_14_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_15_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_16_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_17_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_18_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_20_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_21_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_22_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_24_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_26_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_28_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_32_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_40_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_48_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_60_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_72_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
