#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_8_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_9_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_10_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_11_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_12_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_13_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_14_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_15_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_16_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_17_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_18_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_20_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_21_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_22_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_24_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_26_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_28_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_32_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_40_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_48_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_60_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_72_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedBlack_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
