#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_8;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_9;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_10;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_11;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_12;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_13;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_14;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_15;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_16;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_17;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_18;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_20;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_21;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_22;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_24;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_26;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_28;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_32;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_40;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_48;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_60;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_72;
extern const ILI9341_t3_font_t InconsolataSemiExpandedSemiBold_96;

#ifdef __cplusplus
} // extern "C"
#endif
