#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_8;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_9;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_10;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_11;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_12;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_13;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_14;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_15;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_16;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_17;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_18;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_20;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_21;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_22;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_24;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_26;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_28;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_32;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_40;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_48;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_60;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_72;
extern const ILI9341_t3_font_t InconsolataUltraExpandedSemiBold_96;

#ifdef __cplusplus
} // extern "C"
#endif
