#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_8;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_9;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_10;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_11;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_12;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_13;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_14;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_15;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_16;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_17;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_18;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_20;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_21;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_22;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_24;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_26;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_28;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_32;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_40;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_48;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_60;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_72;
extern const ILI9341_t3_font_t InconsolataUltraCondensedMedium_96;

#ifdef __cplusplus
} // extern "C"
#endif
