#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_8;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_9;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_10;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_11;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_12;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_13;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_14;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_15;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_16;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_17;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_18;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_20;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_21;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_22;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_24;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_26;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_28;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_32;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_40;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_48;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_60;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_72;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraBold_96;

#ifdef __cplusplus
} // extern "C"
#endif
