#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_8;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_9;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_10;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_11;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_12;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_13;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_14;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_15;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_16;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_17;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_18;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_20;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_21;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_22;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_24;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_26;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_28;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_32;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_40;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_48;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_60;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_72;
extern const ILI9341_t3_font_t InconsolataExtraCondensedMedium_96;

#ifdef __cplusplus
} // extern "C"
#endif
