#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_8;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_9;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_10;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_11;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_12;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_13;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_14;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_15;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_16;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_17;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_18;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_20;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_21;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_22;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_24;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_26;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_28;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_32;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_40;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_48;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_60;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_72;
extern const ILI9341_t3_font_t InconsolataSemiCondensedExtraBold_96;

#ifdef __cplusplus
} // extern "C"
#endif
