#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_8;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_9;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_10;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_11;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_12;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_13;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_14;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_15;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_16;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_17;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_18;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_20;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_21;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_22;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_24;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_26;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_28;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_32;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_40;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_48;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_60;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_72;
extern const ILI9341_t3_font_t InconsolataSemiExpandedExtraBold_96;

#ifdef __cplusplus
} // extern "C"
#endif
