#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_8;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_9;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_10;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_11;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_12;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_13;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_14;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_15;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_16;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_17;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_18;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_20;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_21;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_22;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_24;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_26;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_28;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_32;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_40;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_48;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_60;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_72;
extern const ILI9341_t3_font_t InconsolataUltraCondensedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
