#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_8;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_9;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_10;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_11;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_12;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_13;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_14;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_15;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_16;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_17;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_18;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_20;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_21;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_22;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_24;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_26;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_28;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_32;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_40;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_48;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_60;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_72;
extern const ILI9341_t3_font_t InconsolataUltraExpandedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
