#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_8;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_9;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_10;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_11;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_12;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_13;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_14;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_15;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_16;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_17;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_18;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_20;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_21;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_22;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_24;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_26;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_28;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_32;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_40;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_48;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_60;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_72;
extern const ILI9341_t3_font_t InconsolataExtraExpandedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
