#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_8;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_9;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_10;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_11;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_12;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_13;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_14;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_15;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_16;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_17;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_18;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_20;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_21;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_22;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_24;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_26;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_28;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_32;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_40;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_48;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_60;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_72;
extern const ILI9341_t3_font_t IBMPlexSansDevanagariExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
