#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_8;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_9;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_10;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_11;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_12;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_13;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_14;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_15;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_16;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_17;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_18;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_20;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_21;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_22;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_24;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_26;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_28;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_32;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_40;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_48;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_60;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_72;
extern const ILI9341_t3_font_t IBMPlexSansThaiLoopedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif
