#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_8_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_9_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_10_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_11_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_12_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_13_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_14_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_15_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_16_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_17_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_18_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_20_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_21_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_22_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_24_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_26_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_28_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_32_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_40_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_48_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_60_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_72_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedMedium_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
