#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_8_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_9_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_10_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_11_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_12_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_13_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_14_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_15_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_16_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_17_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_18_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_20_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_21_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_22_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_24_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_26_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_28_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_32_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_40_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_48_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_60_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_72_Italic;
extern const ILI9341_t3_font_t IBMPlexSansCondensedExtraLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
