#pragma once
#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_8_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_9_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_10_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_11_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_12_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_13_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_14_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_15_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_16_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_17_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_18_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_20_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_21_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_22_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_24_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_26_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_28_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_32_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_40_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_48_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_60_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_72_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedExtraLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif
